version: '3'

services:
  meme_fastapi:
    container_name: meme_fastapi
    build: 
      context: .
    env_file:
      - .env
    ports:
      - 9999:8000
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: db_app
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    env_file:
      - .env
