version: '3'

networks:
  app-tier:
    driver: bridge

services:
  minio:
    image: 'bitnami/minio:latest'
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    env_file:
      - minio.env
    networks:
      - app-tier

  meme_fastapi:
    container_name: meme_fastapi
    image: context .
    networks:
      - app-tier
    env_file:
      - minio.env

  db_app:
    image: postgres:16
    container_name: db_app
    command: -p 5435
    expose:
      - 5435
    env_file:
      - postgres.env
